spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sivi_mart
    username: root
    password: 123456
  jpa:
    properties:
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: create
      #create: chiến lược tạo bảng từ entity: create là luôn tạo mới khi chạy
    show-sql: true

server:
  port: 8080